### ISSUE TITLE
[EPIC] Thrust Documentation Improvements

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/thrust#1875]
This is a tracking issue to collect all requests related to documentation improvements.

We will be closing out stale doc request issues and reflecting them here as appropriate.

```[tasklist]
### Tasks
- [ ] Add documentation for `thrust::cuda::par.on()` https://github.com/NVIDIA/thrust/issues/1013#issuecomment-1443621452
- [ ] https://github.com/NVIDIA/thrust/issues/1771
- [ ] https://github.com/NVIDIA/thrust/issues/1709
- [ ] https://github.com/NVIDIA/thrust/issues/876
```

**Comment by jrhemstad** [comment]
Closing in favor of https://github.com/NVIDIA/cccl/issues/51
